### PR TITLE
Add fullOuterJoin to RDD. Add tests for outer joins.

### PR DESCRIPTION
**Pull request by pganssle**
This addresses issue #7, implementing it the same way other joins are implemented, and adds (skipped) tests for Issue #8.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Thanks for the PR. Looks great!

Doctests get confused with the unicode literal and this is a problem that has been bugging me for a while with other tests as well. That's why I avoided to use any strings in doctests (which is also weird). I just found this workaround and I am going to try this: https://github.com/gnublade/doctest-ignore-unicode

I should probably add to the README, that `python setup.py test` does not run the doctests but `nosetests` does. Sorry.

**Comment by pganssle** [comment]
Yeah, I actually had the python setup.py tests hang for whatever reason the first time I ran them anyway, so I was just relying on the CI to run the tests for me. It's not an ideal situation, but I don't love my current dev environment anyway (Windows laptop), so I try not to fight with it too much until I have a chance to rip it all out and start over.

**Comment by pganssle** [comment]
@svenkreiss Since it's working on python 2.7 and the doctest is just a problem in python 3.x, should I just put in a +skip for now, and you can remove that when you have the workaround installed, or would you prefer I switch to non-string keys?

**Comment by svenkreiss** [comment]
Ah, I understand. Don't worry. Just leave it as is. I'll try locally whether this nose plugin fixes it. If yes, then the merge will fix Python 3 automatically.

**Comment by svenkreiss** [comment]
Merged and all green now. Thanks a lot!
Will do a new release soon.

**Pull request merged**
