### PR TITLE
Checking with flake8

### PR DESCRIPTION
**Pull request by svaningelgem**
A few of the comments were to the point.

This PR needs to be considered after merging #147 as there are very little differences between them.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Can you outline what we gain from flake8?

**Comment by svaningelgem** [comment]
Flake added some more remarks that were not picked up by pylint neither by pycodestyle.
In this case if I re-read the commits I made:
- `except ImportError as e`: not using `e` can allow you to drop the `e`.
- usage of "l" (is an ambiguous character)
- checking of shadowing variables from another scope

If these can be handled by either of the existing tools, I'm all for it, but flake8 gave these (in my opinion valid) warnings, so I think there is an added value.

**Comment by svenkreiss** [comment]
flake8 doesn't seem relevant. Let's not add this until there is a need. pylint is evolving too.

**Comment by svaningelgem** [comment]
> flake8 doesn't seem relevant. Let's not add this until there is a need. pylint is evolving too.

Ok

**Pull request closed without merging**
